# Logging namespace
logging:
  level:
    ROOT: INFO

# Application server namespace
server:
  port: 8080

  servlet:
    contextPath: /gerenciador-energia
    session:
      tracking-modes: cookie
      cookie:
        http-only: true

  compression:
    enabled: true

# JSF namespace
joinfaces:
  jsf:
    project-stage: Production
    state-saving-method: client

  primefaces:
    fontAwesome: true
    theme: bootstrap
    mobile:
      theme: bootstrap
